FROM golang:1.24-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Build with ldflags to strip debug info for smaller image
RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-s -w" -o controller-app main.go

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/controller-app .
# Needed for sqlite
RUN apk add --no-cache sqlite-libs sqlite 

# Create DB dir
RUN mkdir -p /app/db

EXPOSE 8080
ENTRYPOINT ["/app/controller-app", "controller"]
