// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"config-manager/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigRepository creates a new instance of MockConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigRepository {
	mock := &MockConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigRepository is an autogenerated mock type for the ConfigRepository type
type MockConfigRepository struct {
	mock.Mock
}

type MockConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigRepository) EXPECT() *MockConfigRepository_Expecter {
	return &MockConfigRepository_Expecter{mock: &_m.Mock}
}

// GetLatest provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) GetLatest() (*domain.GlobalConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *domain.GlobalConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*domain.GlobalConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.GlobalConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GlobalConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigRepository_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type MockConfigRepository_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
func (_e *MockConfigRepository_Expecter) GetLatest() *MockConfigRepository_GetLatest_Call {
	return &MockConfigRepository_GetLatest_Call{Call: _e.mock.On("GetLatest")}
}

func (_c *MockConfigRepository_GetLatest_Call) Run(run func()) *MockConfigRepository_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigRepository_GetLatest_Call) Return(globalConfig *domain.GlobalConfig, err error) *MockConfigRepository_GetLatest_Call {
	_c.Call.Return(globalConfig, err)
	return _c
}

func (_c *MockConfigRepository_GetLatest_Call) RunAndReturn(run func() (*domain.GlobalConfig, error)) *MockConfigRepository_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) Save(config *domain.GlobalConfig) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.GlobalConfig) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConfigRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - config *domain.GlobalConfig
func (_e *MockConfigRepository_Expecter) Save(config interface{}) *MockConfigRepository_Save_Call {
	return &MockConfigRepository_Save_Call{Call: _e.mock.On("Save", config)}
}

func (_c *MockConfigRepository_Save_Call) Run(run func(config *domain.GlobalConfig)) *MockConfigRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.GlobalConfig
		if args[0] != nil {
			arg0 = args[0].(*domain.GlobalConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigRepository_Save_Call) Return(err error) *MockConfigRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigRepository_Save_Call) RunAndReturn(run func(config *domain.GlobalConfig) error) *MockConfigRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
