// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"config-manager/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentRepository creates a new instance of MockAgentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRepository {
	mock := &MockAgentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentRepository is an autogenerated mock type for the AgentRepository type
type MockAgentRepository struct {
	mock.Mock
}

type MockAgentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRepository) EXPECT() *MockAgentRepository_Expecter {
	return &MockAgentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) Create(agent *domain.Agent) error {
	ret := _mock.Called(agent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Agent) error); ok {
		r0 = returnFunc(agent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAgentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - agent *domain.Agent
func (_e *MockAgentRepository_Expecter) Create(agent interface{}) *MockAgentRepository_Create_Call {
	return &MockAgentRepository_Create_Call{Call: _e.mock.On("Create", agent)}
}

func (_c *MockAgentRepository_Create_Call) Run(run func(agent *domain.Agent)) *MockAgentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Agent
		if args[0] != nil {
			arg0 = args[0].(*domain.Agent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRepository_Create_Call) Return(err error) *MockAgentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRepository_Create_Call) RunAndReturn(run func(agent *domain.Agent) error) *MockAgentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) GetByID(id string) (*domain.Agent, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.Agent, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.Agent); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAgentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *MockAgentRepository_Expecter) GetByID(id interface{}) *MockAgentRepository_GetByID_Call {
	return &MockAgentRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockAgentRepository_GetByID_Call) Run(run func(id string)) *MockAgentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRepository_GetByID_Call) Return(agent *domain.Agent, err error) *MockAgentRepository_GetByID_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockAgentRepository_GetByID_Call) RunAndReturn(run func(id string) (*domain.Agent, error)) *MockAgentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
